# Generated by Django 4.1 on 2022-09-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_remove_properties_type_liked_properties_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='type',
        ),
        migrations.AddField(
            model_name='properties',
            name='type',
            field=models.ManyToManyField(to='apiapp.typetable'),
        ),
    ]
