# Generated by Django 4.1.1 on 2022-09-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_remove_properties_type_properties_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='location',
        ),
        migrations.RemoveField(
            model_name='typetable',
            name='range_max',
        ),
        migrations.RemoveField(
            model_name='typetable',
            name='range_min',
        ),
        migrations.AddField(
            model_name='properties',
            name='lat',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='properties',
            name='long',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
