# Generated by Django 4.1.1 on 2022-09-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_properties_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
