# Generated by Django 4.1.1 on 2022-10-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_alter_properties_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='liked',
            name='like',
            field=models.BooleanField(default=0),
        ),
    ]
