# Generated by Django 4.1.1 on 2022-10-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_liked_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liked',
            name='like',
        ),
    ]
