# Generated by Django 4.1.1 on 2022-10-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0010_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prop_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.TextField(null=True)),
            ],
        ),
    ]
