# Generated by Django 4.1.1 on 2022-10-14 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0011_prop_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='prop_images',
            name='property_id',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='apiapp.properties'),
        ),
    ]
