# Generated by Django 4.1.1 on 2022-10-14 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiapp', '0013_remove_prop_images_property_id_prop_images_malik_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prop_images',
            name='customer_id',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
