# Generated by Django 4.1.1 on 2022-10-14 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0014_prop_images_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prop_images',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='prop_images',
            name='malik_id',
        ),
        migrations.AddField(
            model_name='prop_images',
            name='property_id',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='apiapp.properties'),
        ),
    ]
