# Generated by Django 4.1.1 on 2022-10-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0018_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='adress',
            field=models.TextField(null=True),
        ),
    ]
