# Generated by Django 4.1.1 on 2022-10-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0019_properties_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='prop_images',
            name='img2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prop_images',
            name='img3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prop_images',
            name='img4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prop_images',
            name='img5',
            field=models.TextField(null=True),
        ),
    ]
