# Generated by Django 4.1.1 on 2022-10-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0020_prop_images_img2_prop_images_img3_prop_images_img4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='url',
            field=models.CharField(default='../assets/save-instagram.png', max_length=255),
        ),
    ]
