# Generated by Django 4.1.1 on 2022-10-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0021_properties_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='url',
        ),
    ]
