# Generated by Django 4.1.1 on 2022-10-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0022_remove_properties_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
