# Generated by Django 4.1.1 on 2022-10-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0024_catogary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catogary',
            name='full_fury',
        ),
        migrations.AddField(
            model_name='catogary',
            name='full_fur',
            field=models.BooleanField(default=False),
        ),
    ]
