# Generated by Django 4.1.1 on 2022-10-31 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0026_properties_catogary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='type',
        ),
    ]
