# Generated by Django 4.1.1 on 2022-11-07 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiapp', '0027_remove_properties_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='catogary',
            field=models.ManyToManyField(related_name='categories', to='apiapp.catogary'),
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complant', models.CharField(max_length=255)),
                ('property', models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='apiapp.properties')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
